name: PR 描述检查

on:
  workflow_call:

permissions:
  pull-requests: read

jobs:
  pr-body-check:
    name: 检查 PR 描述
    runs-on: ubuntu-latest
    steps:
      - name: 检查必要小节
        uses: CUHKSZ-ITSO-Dev/.github/actions/check-pr-body@main
        with:
          body: ${{ github.event.pull_request.body }}
